version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    assignees:
      - 'maguru-admin'
    reviewers:
      - 'maguru-devops'
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: 'actions/checkout'
        versions: ['3.x'] # Pertahankan v4
      - dependency-name: 'actions/setup-node'
        versions: ['3.x'] # Pertahankan v4

  # Maintain dependencies for npm (yarn)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: increase
    commit-message:
      prefix: 'dep'
      include: 'scope'
    assignees:
      - 'maguru-admin'
    reviewers:
      - 'maguru-dev'
    allow:
      - dependency-type: 'direct'
    open-pull-requests-limit: 10
    groups:
      testing:
        patterns:
          - '@testing-library/*'
          - 'jest*'
          - '@types/jest'
        update-types:
          - 'minor'
          - 'patch'
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
        update-types:
          - 'minor'
          - 'patch'
