import { Course } from '../types'

export const metadataCourse: Course[] = [
  {
    id: '1',
    title: 'Petualangan Matematika Nusantara',
    description: 'Belajar matematika dengan cerita petualangan di kepulauan Indonesia',
    thumbnail: '/globe.svg ',
    status: 'PUBLISHED',
    students: 1250,
    lessons: 24,
    duration: '8 jam',
    rating: 4.8,
    category: 'Matematika',
    createdAt: new Date(2024, 0, 15),
    creatorId: '1',
    updatedAt: new Date(2024, 0, 15),
  },
  {
    id: '2',
    title: 'Legenda Bahasa Indonesia',
    description: 'Menguasai bahasa Indonesia melalui cerita rakyat dan legenda',
    thumbnail: '/globe.svg',
    status: 'DRAFT',
    students: 0,
    lessons: 18,
    duration: '6 jam',
    rating: 0,
    category: 'Bahasa',
    createdAt: new Date(2024, 1, 20),
    creatorId: '1',
    updatedAt: new Date(2024, 1, 20),
  },
  {
    id: '3',
    title: 'Sains Alam Magis',
    description: 'Eksplorasi sains dengan pendekatan fantasy dan eksperimen menarik',
    thumbnail: '/globe.svg',
    status: 'PUBLISHED',
    students: 890,
    lessons: 32,
    duration: '12 jam',
    rating: 4.6,
    category: 'Sains',
    createdAt: new Date(2024, 0, 8),
    creatorId: '1',
    updatedAt: new Date(2024, 0, 8),
  },
]
