name: Deploy to Staging [DISABLED]

# Mendefinisikan event yang akan memicu workflow ini
on:
  push:
    branches: [develop]
  workflow_run:
    workflows: ['CI Pipeline', 'Build Pipeline']
    types:
      - completed
    branches: [develop]

# Definisikan jobs yang akan dijalankan
jobs:
  # Job untuk deploy aplikasi ke staging
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    # Menonaktifkan deployment untuk tahap pengembangan MVP
    if: false # Deployment dinonaktifkan sampai MVP selesai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Deploy to Vercel (staging)
        id: deploy
        uses: amondnet/vercel-action@v25
        continue-on-error: true
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Retry deployment if failed
        if: steps.deploy.outcome == 'failure'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Create deployment summary
        if: success()
        run: |
          echo "### Deployment Results 🚀" >> $GITHUB_STEP_SUMMARY
          echo "✅ Application deployed to Staging environment" >> $GITHUB_STEP_SUMMARY
          echo "🔗 URL: ${{ steps.deploy.outputs.preview-url || 'https://staging.maguru.app' }}" >> $GITHUB_STEP_SUMMARY

      - name: Post deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Deployment successful! Application deployed to staging environment."
          else
            echo "Deployment failed. Check logs for more information."
          fi
